### ISSUE TITLE
Valid emoji isn't in the unicode map

### ISSUE THREAD

**Issue by Jasperav** [rossmacarthur/emojis#14]
👪🏻 this is a family, it isn't in the map (emojis::get). Maybe more emojis are not in the map which are valid emojis.

**Comment by rossmacarthur** [comment]
The emoji you have here is not a valid emoji. `"\u{1f46a}\u{1f3fb}"` (👪🏻) isn't in the Unicode [emoji test list](https://unicode.org/Public/emoji/15.1/emoji-test.txt) which is what this crate uses as the source of truth. This appears to be a family `"\u{1f46a}"` (👪) followed by a light skin tone char `"\u{1f3fb}"` ( 🏻). In my font this doesn't render as a light skin tone but instead as just the neutral 👪. Additionally, since it is not a valid emoji the way it is rendered seems to differ in apps/fonts, for example:
<img width="45" alt="image" src="https://github.com/rossmacarthur/emojis/assets/17109887/a7a11700-00d8-4436-9535-ddf5c2db9445">

It might be possible to make this crate handle this, but I would like to know what is the source of this emoji?

**Comment by Jasperav** [comment]
@rossmacarthur You are right, I don't believe this is a valid emoji. I don't know anymore where I got the emoji from, so I close this issue.
